  image-test:
    needs: push
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Cloud One Container Security Scan Action
        uses: felipecosta09/Deep-Security-Smart-Check-Scan-Action@v1.0.2
        with:
          # Mandatory
          DSSC_IMAGE_NAME: registry.hub.docker.com/raphabot/java-goof # Change with your image path.
          # DSSC_IMAGE_NAME: $IMAGE_PATH
          DSSC_SMARTCHECK_HOST: c1cs.nedemos.io
          DSSC_SMARTCHECK_USER: endtoenddemo
          DSSC_SMARTCHECK_PASSWORD: ${{ secrets.DSSC_SMARTCHECK_PASSWORD }}
          DSSC_IMAGE_PULL_AUTH: '{"username": "${{ secrets.DOCKER_USERID }}","password": "${{ secrets.DOCKER_KEY }}"}'

          # Optional
          DSSC_INSECURE_SKIP_TLS_VERIFY: true
          DSSC_INSECURE_SKIP_REGISTRY_TLS_VERIFY: false
          # DSSC_PREREGISTRY_SCAN: false
          # DSSC_PREREGISTRY_HOST: myorg.com
          # DSSC_PREREGISTRY_USER: admin
          # DSSC_PREREGISTRY_PASSWORD: 12345
          # DSSC_RESULTS_FILE: /results.json
          DSSC_FINDINGS_THRESHOLD: '{"malware": 100, "vulnerabilities": { "defcon1": 100, "critical": 100, "high": 100 }, "contents": { "defcon1": 100, "critical": 100, "high": 100 }, "checklists": { "defcon1": 100, "critical": 100, "high": 100 }}'
